apiVersion: v1
kind: Service
metadata:
    labels:
        name: eth-monitor
    name: eth-monitor
spec:
    ports:
        - port: 3000
          targetPort: 3000
    selector:
        name: eth-monitor
