apiVersion: v1
kind: ReplicationController
metadata:
    labels:
        name: geth-miner
    name: geth-miner
spec:
    replicas: 1
    selector:
        name: geth-miner
    template:
        metadata:
            labels:
                name: geth-miner
        spec:
            containers:
                - name: geth-miner
                  image: j4ustin/geth-testnet-cluster
                  command:
                      - "geth"
                      - "--mine"
                      - "--minerthreads"
                      - "1"
                      - "--identity"
                      - "\"kubernodeth\""
                      - "--genesis"
                      - "/etc/testnet/CustomGenesis.json"
                      - "--rpc"
                      - "--rpcport"
                      - "8080"
                      - "--rpccorsdomain"
                      - "\"*\""
                      - "--datadir"
                      - "\"/etc/testnet\""
                      - "--port"
                      - "30303"
                      - "--nodiscover"
                      - "--autodag"
                      - "--networkid"
                      - "9087"
                      - "--nat"
                      - "any"
            ports:
                - containerPort: 8080
                - containerPort: 30303
            resources:
                limits:
                    cpu: "0.25"
